name: Build Windows EXE

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  
jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build EXE
        run: |
          pyinstaller --onefile main.py

      - name: Upload artifact to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*.exe
            bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create ZIP package
        run: |
          mkdir package
          copy dist\main.exe package\
          copy bin\ffmpeg.exe package\
          copy bin\ffprobe.exe package\
          powershell Compress-Archive -Path package\* -DestinationPath release.zip
      
      - name: Upload ZIP to release
        uses: softprops/action-gh-release@v1
        with:
          files: release.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


